### PR TITLE
Translation for Chinese (Traditional)

### PR DESCRIPTION
**Pull request by birkhofflee**
I've done the translation, this closes issue #5.

### CODE REVIEW

**Comment by birkhofflee** [comment]
I also wonder the license you are using for this tutorial, I see the code part is MIT licensed

**Comment by humphd** [comment]
@BirkhoffLee, first of all, **thank you** for putting so much time into this.  I think it's great that you've made this more accessible to a larger audience.  I know this was a lot of work.

I'm not equipped to comment on the translation as such, but perhaps someone else will jump in and provide some guidance in this PR.  If not, we'll just go with it and let people correct things in new PRs later.  Once I land this I'll add you as a contributor, so you can maintain your Chinese version.

A couple of things that would be good to do:
* Let's remove the reference to the Chinese Caffe macOS instructions you wrote in the English `README.md`, and just leave it in your translation. Anyone wanting the Chinese version of those instructions is better served reading your version at this point.
* In your translation, let's provide a link back to the English as well, for those who land on this via a search.  At the top of yours, let's do `Author: David Humphrey (original English version)` and make `English version` a link back to `README.md`. 

In terms of the license, I used MIT because this was a mix of code and documentation, and it covers both nicely.

I'm teaching my students how to do PRs and use github right now, so I'll wait until you fix those few things above, and then land it later in the week when I can show them.

**Comment by birkhofflee** [comment]
You're welcome, I've done the modifications and thanks again for your great writeup!

**Comment by humphd** [comment]
Hey @BirkhoffLee, I've added you as a Collaborator to the repo.  Feel free to manage the `README_zh-tw.md` file as you need to.

Thanks again for your hard work on this translation!

**Comment by birkhofflee** [comment]
You're welcome, I'm always willing to contribute to the community.

**Pull request merged**
