### PR TITLE
Add docker quick start guide

### PR DESCRIPTION
**Pull request by swarshah**
It's a pain to get Caffe + DIGITS working and takes a lot of time to get started. That's why I have added this so that who has docker installed can get started easily.

I wasn't sure about the location where to put this so I have added to the bottom of installation. 
Feel free to change it.

Thanks,
Swar

### CODE REVIEW

**Comment by birkhofflee** [comment]
Just notice that you can do `docker port $(docker run -dP kaixhin/digits)`

**Comment by swarshah** [comment]
Thanks, @BirkhoffLee.
That's much cleaner than what I did.
I'll update that.

**Comment by humphd** [comment]
This is great, thanks @SwarShah!  I'm not a regular Docker user, so let me confirm a few things with you:

* Why use `kaixhin/digits` vs. the official one at `https://hub.docker.com/r/nvidia/digits/`?
* Will people who use this need to specify anything special for data retention afterward (i.e., do they need some kind of fs/data volume in order for the model files, datasets, etc. to persist)?

**Comment by birkhofflee** [comment]
@humphd I've dug into these two images and here's some useful information:

> nVidia's: https://gitlab.com/nvidia/caffe/blob/master/0.15/Dockerfile
  https://gitlab.com/nvidia/cuda/blob/ubuntu14.04/7.5/runtime/cudnn5/Dockerfile
  https://gitlab.com/nvidia/cuda/blob/ubuntu14.04/7.5/runtime/Dockerfile

> Kaixhin's: https://github.com/Kaixhin/dockerfiles/blob/master/digits/Dockerfile
  https://github.com/Kaixhin/dockerfiles/blob/master/digits/deps/Dockerfile

I guess that the only difference of these two images is just one's using GPU and one's using CPU. And for the second question I don't think one needs to set up any volumes for this image since you can upload/download anything you want right from the DIGITS web interface.

**Comment by swarshah** [comment]
@humphd I think @BirkhoffLee is right regarding the difference.

And for the second part: yes you can either upload/download directly from the web interface or you can ssh into the container and put files over there and give path in the web interface.

**Comment by birkhofflee** [comment]
@SwarShah I found that kaixhin/digits exposes container port 5000:  
`EXPOSE 5000` (https://hub.docker.com/r/kaixhin/digits/~/dockerfile/)

So a better idea will be:  
```
$ docker run -d -p 8080:5000 kaixhin/digits
```

Then just open `http://localhost:8080` and all done.

**Comment by birkhofflee** [comment]
In addition, you don't actually need to pull the image before running, running a container will automatically pull the image you want, so you can remove this:
```
Pull the docker image from Docker Hub.

\```bash
docker pull kaixhin/digits
\```
```

**Comment by swarshah** [comment]
@BirkhoffLee Perfect!
From few lines of instruction, we are at a one-liner now.
Thanks.

**Comment by birkhofflee** [comment]
And @humphd I've tested this and it's working fine, so if you want you can just merge. Add a `-v` option for mounting the repo dir into the container would be better. (I found that the files could be only individually uploaded, sorry :p)

**Comment by humphd** [comment]
I've tested this, corrected a typo, and it works amazingly.  I've also updated the README slightly to better reflect the 2 installation paths.

Thanks again for this!

**Pull request merged**
